models:
  gemini_2.5_flash: "gemini-2.5-flash-preview-04-17"
  gemini_2.0_flash: "gemini-2.0-flash"
  gpt_4o: "github/gpt-4o"
  gpt_41: "github/gpt-4.1"

templates:
  cv: "data/SajjalaSreekarReddy_CV.docx"
  cover_letter: "data/CoverLetter_Template.docx"

# Output paths
output:
  cv_path: "output/cv"
  cover_letter_path: "output/cover_letters"
  job_data_path: "jobs"

# Job search parameters
keywords: "machine learning engineer"
locations:
  - "Germany"
  - "Netherlands"
job_type: "full-time"
experience_level: "entry-level"
posting_within: "2 weeks"

# Agent settings
initial_draft_model: "gpt_41"
critic_model: "gpt_4o"
fact_check_model: "gemini"
reviser_model: "gpt_4o"
grammar_check_model: "gemini"
final_draft_model: "gpt_41"

max_loop_iterations: 5
logging_level: "INFO"