templates:
  cv: "data/SajjalaSreekarReddy_CV.docx"
  cover_letter: "data/CoverLetter_Template.docx"

# Output paths
output:
  cv_path: "output/cv"
  cover_letter_path: "output/cover_letters"
  job_data_path: "jobs"
