model_list:
  - model_name: gpt-4o
    litellm_params:
      model: github/gpt-4o
      api_key: os.environ/GITHUB_API_KEY_4o
  - model_name: gpt-4.1
    litellm_params:
      model: github/gpt-4.1
      api_key: os.environ/GITHUB_API_KEY_41
